config/routes.rb
Rails.application.routes.draw do
  root to: "buckets#index"
  resources :buckets do
    resources :file_uploads, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
  has_many_attached :files
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  before_action :set_bucket, only: [:show, :edit, :update, :destroy]

  # GET /buckets
  # GET /buckets.json
  def index
    @buckets = Bucket.all
  end

  # GET /buckets/1
  # GET /buckets/1.json
  def show
  end

  # GET /buckets/new
  def new
    @bucket = Bucket.new
  end

  # GET /buckets/1/edit
  def edit
  end

  # POST /buckets
  # POST /buckets.json
  def create
    @bucket = Bucket.new(bucket_params)

    respond_to do |format|
      if @bucket.save
        format.html { redirect_to @bucket, notice: 'Bucket was successfully created.' }
        format.json { render :show, status: :created, location: @bucket }
      else
        format.html { render :new }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buckets/1
  # PATCH/PUT /buckets/1.json
  def update
    respond_to do |format|
      if @bucket.update(bucket_params)
        format.html { redirect_to @bucket, notice: 'Bucket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bucket }
      else
        format.html { render :edit }
        format.json { render json: @bucket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buckets/1
  # DELETE /buckets/1.json
  def destroy
    @bucket.destroy
    respond_to do |format|
      format.html { redirect_to buckets_url, notice: 'Bucket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bucket
      @bucket = Bucket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bucket_params
      params.require(:bucket).permit(:name)
    end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  def new
    @bucket = Bucket.find(params[:bucket_id])
  end

  def create
    @bucket = Bucket.find(params[:bucket_id])
    @bucket.files.attach(params[:bucket][:files])
    redirect_to bucket_path(@bucket)
  end

  def destroy
    @bucket = Bucket.find(params[:bucket_id])
    @bucket.files.find(params[:id]).purge
    redirect_to bucket_path(@bucket)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/buckets/_form.html.erb
<%= form_with(model: bucket, local: true) do |form| %>
  <% if bucket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bucket.errors.count, "error") %> prohibited this bucket from being saved:</h2>

      <ul>
      <% bucket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buckets/edit.html.erb
<h1>Editing Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Show', @bucket %> |
<%= link_to 'Back', buckets_path %>

app/views/buckets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buckets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buckets.each do |bucket| %>
      <tr>
        <td><%= bucket.name %></td>
        <td><%= link_to 'Show', bucket %></td>
        <td><%= link_to 'Edit', edit_bucket_path(bucket) %></td>
        <td><%= link_to 'Destroy', bucket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bucket', new_bucket_path %>

app/views/buckets/new.html.erb
<h1>New Bucket</h1>

<%= render 'form', bucket: @bucket %>

<%= link_to 'Back', buckets_path %>

app/views/buckets/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @bucket.name %></h3>

<%= link_to 'Edit', edit_bucket_path(@bucket) %> |
<%= link_to 'Back', buckets_path %> |
<%= link_to 'Upload Files', new_bucket_file_upload_path(@bucket) %>


<h5>Files</h5>

<ul>
  <% @bucket.files.each do |file| %>
    <li>
      <%= link_to file.filename, url_for(file) %>
      <%= link_to "X", bucket_file_upload_path(@bucket, file), method: :delete, data: { confirm: "Tem certeza?" } %>
    </li>
  <% end %>
</ul>

app/views/file_uploads/new.html.erb
<h1>Upload for Bucket <%= @bucket.name %></h1>

<h4 class="progress" style="display: none">Progress: <span class="progress_count"></span>%</h4>

<%= form_with model: @bucket, url: bucket_file_uploads_path(@bucket), method: :post, id: "upload_file", local: true do |f| %>
  <%= f.file_field :files, multiple: true, direct_upload: true %><br /><br />
  <%= f.submit 'Upload' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeBucket</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>